### ISSUE TITLE
Error on npm run install:project

### ISSUE THREAD

**Issue by AircGroup** [Averito/Averlist#9]
![Скриншот 24-06-2022 06 17 44](https://user-images.githubusercontent.com/93317344/175379917-3dae175a-6b8b-4bd6-bba9-26df2bba541b.png)
Я пытаюсь установить зависимости при помощи npm run install:project но у них проблемы.(скрин прикрепил) такая ситуация в linux(только сегодня поставил все) и windows(windows скрин версий прикрепил).
![Скриншот 24-06-2022 06 19 17](https://user-images.githubusercontent.com/93317344/175380159-f4dd23ba-14aa-4adf-8069-3f37afa239c4.png)

**Comment by AircGroup** [comment]
[2022-06-23T19_26_48_210Z-debug.log](https://github.com/Averito/Averlist/files/8970300/2022-06-23T19_26_48_210Z-debug.log)
дебаг лог.

**Comment by Averito** [comment]
> ![Скриншот 24-06-2022 06 17 44](https://user-images.githubusercontent.com/93317344/175379917-3dae175a-6b8b-4bd6-bba9-26df2bba541b.png)
> Я пытаюсь установить зависимости при помощи npm run install:project но у них проблемы.(скрин прикрепил) такая ситуация в linux(только сегодня поставил все) и windows(windows скрин версий прикрепил).
> ![Скриншот 24-06-2022 06 19 17](https://user-images.githubusercontent.com/93317344/175380159-f4dd23ba-14aa-4adf-8069-3f37afa239c4.png)
>  

Версия ноды старая, нужна >= 14

**Comment by Averito** [comment]
> ![Скриншот 24-06-2022 06 17 44](https://user-images.githubusercontent.com/93317344/175379917-3dae175a-6b8b-4bd6-bba9-26df2bba541b.png)
> Я пытаюсь установить зависимости при помощи npm run install:project но у них проблемы.(скрин прикрепил) такая ситуация в linux(только сегодня поставил все) и windows(windows скрин версий прикрепил).
> ![Скриншот 24-06-2022 06 19 17](https://user-images.githubusercontent.com/93317344/175380159-f4dd23ba-14aa-4adf-8069-3f37afa239c4.png)
>  

Чтобы поставить на Linux последнюю версию ноды нужно использовать nvm (Node version manager).
Так что сперва требуется установить его.
